### ISSUE TITLE
Mac (Linux)

### ISSUE THREAD

**Issue by rkusa** [myVSR/thesis-template-latex#1]
Ich hatte das Template für meine MA für Mac angepasst. Also zB ein Makefile statt einem Batch File und ansonsten paar Sachen aufgeräumt. Die Frage wäre jetzt, lohnt sich die Arbeit, dieses Template für die Max/Linux User aufzubereiten oder überlassen wir das jedem selber? Wenn es sich lohnt, sollten wir dafür ein neues Repo machen, oder sollten wir Versuchen es hier zu integrieren/mergen?

**Comment by tr3ddy** [comment]
Da es sicher den ein oder anderen Mac/Linux Nutzer gibt, der bei uns eine Abschlussarbeit schreibt, fände ich es nicht schlecht, wenn wir da eine angenehmere Vorlage anbieten. Gerade wenn du das für deine MA bereits gemacht hast, sollte der Aufwand, dass noch einmal aufzubereiten, nicht zu groß sein.
Ich wäre für eine Integration in dieses Repo, falls möglich. Damit bleiben die Latex-Source-Files immer auf dem gleichen Stand und benötigen bei etwaigen Änderungen des Templates keine doppelte Pflege.
